export const BRAND = {
  company: "Cole Air, Inc.",
  phone: "(337) 855-6628",
  phoneHref: "+13378556628",
  phoneAlt: "(337) 427-8291",
  phoneAltHref: "+13374278291",
  email: "Admin@ColeAir.net",
  url: "https://www.coleair.net",
  address: {
    street: "620 Marilyn Rd",
    city: "Lake Charles",
    region: "LA",
    postal: "70611",
    country: "US"
  },
  hours: [
    { days: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"], opens: "00:00", closes: "24:00" }
  ],
  serviceAreas: [
    "Lake Charles, LA",
    "Sulphur, LA",
    "Moss Bluff, LA",
    "Westlake, LA",
    "DeQuincy, LA",
    "Hackberry, LA",
    "Iowa, LA",
    "Ragley, LA",
    "Big Lake, LA",
    "Carlyss, LA",
    "Cameron, LA",
    "Gillis, LA",
    "Mossville, LA",
    "Bell City, LA",
    "Vinton, LA",
    "Jennings, LA",
    "Welsh, LA",
    "Prien, LA",
    "Lake Arthur, LA",
    "Calcasieu Parish, LA",
    "Beauregard Parish, LA",
    "Cameron Parish, LA",
    "Jefferson Davis Parish, LA",

  ],
  colors: { blue: "#4aa8ff", orange: "#ff7a00" },
  tagline: "If It Heats or Cools, We Fix It!",
  subtitle: "Complete Heating & Cooling Service for Lake Charles, LA, and Surrounding Areas!",
  description: "Maintenance Plans, Home Performance Testing & Financing Available",
  founded: "1985"
};
